after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_script:
  - gem install bundler
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
dist: trusty
env:
  global:
    - CC_TEST_REPORTER_ID=28469933fef808491c2dc35860c179a139c7083ccd603a7f6d705b8de175e12e
language: ruby
notifications:
  - false
rvm:
  - 2.5.0
script:
  - bundle exec rspec spec
